package: 
  name: pywitness
  version: {{ GIT_DESCRIBE_TAG }}

source: 
  path: ../

build: 
  preserve_egg_dir: True

requirements: 

  build:
    - python >=3.9,<=3.13
    - setuptools
    - pip
    - cython
    - pybind11
    - pytz=2021.3
    - xlrd
    - openpyxl
    - scipy
    - matplotlib
    - ipython
#    - pyreadstat

  run:
    - python >=3.9,<=3.13
    - pytz=2021.3
    - xlrd
    - openpyxl
    - pandas
    - scipy
    - matplotlib
    - ipython
#    - pyreadstat

test:
  imports:

about:
  home: