package: 
  name: pywitness
  version: v1.0

source: 
  git_url: https://github.com/lmickes/pyWitness
  git_rev: v1.0

requirements: 
  build: 
    - python
    - setuptools
    - pip

  run:
    - python
    - ipython
    - matplotlib
    - numpy
    - scipy
    - pandas
    - openpyxl
    - xlrd
    - pyreadstat

test:
  imports:
    - pyWitness

about:
  home: