name: distribute

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:

  make_dist:
    name: Make source and wheel dist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build source and wheel dist
        run: pipx run build 

      - uses: actions/upload-artifact@v3
        with:
          path: dist/*

